/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
//import javax.swing.plaf.fileChooser;
import model.employees;
import model.csvReader;
import java.util.List;
import model.orderEmployees;

/**
 *
 * @author Andrei
 */
public class employeesView extends javax.swing.JFrame {
    private ButtonGroup buttonGroup;
    private List<employees> empleados;
    /**
     * Creates new form employeesView
     */
    public employeesView() {
        initComponents();
        setFrame();
    }
    public void setFrame(){
        this.setTitle("Empleados - HR");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(this.ID_Ordenar);
        buttonGroup.add(this.Apellido_Ordenar);
        buttonGroup.add(this.Departamento_Ordenar);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmpleados = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        ID_Ordenar = new javax.swing.JRadioButton();
        Apellido_Ordenar = new javax.swing.JRadioButton();
        Departamento_Ordenar = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        CargarDatos = new javax.swing.JButton();
        BusquedaId = new javax.swing.JButton();
        AñarirDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 370));
        getContentPane().setLayout(new java.awt.BorderLayout(0, 2));

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 324));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 324));
        jPanel3.setLayout(new java.awt.BorderLayout(0, 2));

        jPanel1.setMinimumSize(new java.awt.Dimension(324, 78));
        jPanel1.setPreferredSize(new java.awt.Dimension(324, 78));
        jPanel1.setLayout(new java.awt.BorderLayout(2, 2));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));

        listaEmpleados.setBorder(null);
        jScrollPane1.setViewportView(listaEmpleados);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Ordenar por", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        ID_Ordenar.setSelected(true);
        ID_Ordenar.setText("ID");
        ID_Ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_OrdenarActionPerformed(evt);
            }
        });
        jPanel6.add(ID_Ordenar);

        Apellido_Ordenar.setText("Apellido");
        Apellido_Ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apellido_OrdenarActionPerformed(evt);
            }
        });
        jPanel6.add(Apellido_Ordenar);

        Departamento_Ordenar.setText("Departamento");
        Departamento_Ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Departamento_OrdenarActionPerformed(evt);
            }
        });
        jPanel6.add(Departamento_Ordenar);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(100, 10, 120, 10));
        jPanel2.setMinimumSize(new java.awt.Dimension(178, 299));
        jPanel2.setPreferredSize(new java.awt.Dimension(178, 299));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        CargarDatos.setText("Cargar datos");
        CargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarDatosActionPerformed(evt);
            }
        });
        jPanel2.add(CargarDatos);

        BusquedaId.setText("Busqueda");
        BusquedaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaIdActionPerformed(evt);
            }
        });
        jPanel2.add(BusquedaId);

        AñarirDatos.setText("Añadir + datos");
        AñarirDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñarirDatosActionPerformed(evt);
            }
        });
        jPanel2.add(AñarirDatos);

        jPanel3.add(jPanel2, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_OrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_OrdenarActionPerformed
        OrdenAmostrar();
    }//GEN-LAST:event_ID_OrdenarActionPerformed

    private void CargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarDatosActionPerformed
        JFileChooser fileChooser = new JFileChooser(); //al igual que un JOptionPane, guarda la ruta del archivo deseado en una variable para
        //facilitar su posterior acceso.
        int fileResultado = fileChooser.showOpenDialog(this);
        if (fileResultado == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            listaEmpleados =  csvReader.leerEmpleados(ruta);
        }
    }//GEN-LAST:event_CargarDatosActionPerformed

    private void Apellido_OrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apellido_OrdenarActionPerformed
        OrdenAmostrar();
    }//GEN-LAST:event_Apellido_OrdenarActionPerformed

    private void Departamento_OrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Departamento_OrdenarActionPerformed
        OrdenAmostrar();
    }//GEN-LAST:event_Departamento_OrdenarActionPerformed

    private void BusquedaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaIdActionPerformed
        Busqueda();
    }//GEN-LAST:event_BusquedaIdActionPerformed

    private void AñarirDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñarirDatosActionPerformed
        //AñadirDatos();
    }//GEN-LAST:event_AñarirDatosActionPerformed

    private void OrdenAmostrar(){
        if (AdvertenciaDatos()){
            return;
        }
            
        if(empleados == null || empleados.isEmpty()){
            return;
        }else{
            //ordenamos segun el radio button seleccionado
            if(ID_Ordenar.isSelected()){
                orderEmployees.OrdenPorId(empleados);   
            }else if(Apellido_Ordenar.isSelected()){
                orderEmployees.OrdenPorApellido(empleados);
            }else{
                orderEmployees.OrdenPorDepartamento(empleados);
            }

            String [] texto  = new String[empleados.size()];
            for (int i = 0; i < texto.length; i++){
                texto[i] = empleados.get(i).toString();
            }
            listaEmpleados.setListData(texto); 
        }
    }
   
    private void Busqueda(){
        if (AdvertenciaDatos()){
            return;
        }   
        
        String buscar = JOptionPane.showInputDialog(this, "Introduce un ID a buscar: ", "Buscador de ID", JOptionPane.QUESTION_MESSAGE);
        if (buscar == null || buscar.isEmpty()){
            JOptionPane.showMessageDialog(this, "Introduce un ID");
            return;
        }
        
        int idBuscar;
        try{
            idBuscar = Integer.parseInt(buscar.trim());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "ID no valido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        employees encontrado = null;
        for ( int i = 0; i < empleados.size(); i++){
            if(empleados.get(i).getEmployee_id() == idBuscar){
                encontrado = empleados.get(i);
            }
        }  
        
        if (encontrado != null){
            listaEmpleados.setListData(new String[] {encontrado.toString()});
        }else{
            JOptionPane.showMessageDialog(this, "Empleado no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /*
    private void AñadirDatos(){
        JFileChooser archivoElegir = new JFileChooser();
        int busqueda = archivoElegir.showOpenDialog(this);
        
        if(busqueda == JFileChooser.APPROVE_OPTION){
            File ubicacion = archivoElegir.getSelectedFile();
            if(!)
        }
    }
    */
    private boolean AdvertenciaDatos(){
        if (empleados == null || empleados.isEmpty()){
             JOptionPane.showMessageDialog(this, "Primero añade carga los datos", "Error", JOptionPane.ERROR_MESSAGE);
             return true;
         }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Apellido_Ordenar;
    private javax.swing.JButton AñarirDatos;
    private javax.swing.JButton BusquedaId;
    private javax.swing.JButton CargarDatos;
    private javax.swing.JRadioButton Departamento_Ordenar;
    private javax.swing.JRadioButton ID_Ordenar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaEmpleados;
    // End of variables declaration//GEN-END:variables
}
